sudo: true
language: python
services:
- docker
before_install:
- docker build -t joriskok1/frappantchinees .
- docker-compose up -d
- sleep 5
- docker ps -a
script:
- docker exec frappantchinees_web_1 (cd tests && aloe)
after_failure:
- docker ps -a
- docker volume ls
after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push joriskok1/frappantchinees
